include: "https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml"

.vars-devel:
  variables:
    MANIFEST_PATH: "org.gnome.gitlab.johannesjh.favagtk.devel.json"
    FLATPAK_MODULE: "favagtk"
    APP_ID: "org.gnome.gitlab.johannesjh.favagtk"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "org.gnome.gitlab.johannesjh.favagtk.devel.flatpak"
    CONFIG_OPTS: >-
      -Dprofile=devel

# Build Flatpak for x86_64
flatpak@x86_64:
  extends: ['.flatpak@x86_64', '.vars-devel']

# Build Flatpak for aarch64
flatpak@aarch64:
  extends: ['.flatpak@aarch64', '.vars-devel']
