include: "https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml"

flatpak:
  image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master"
  variables:
    MANIFEST_PATH: "org.gnome.gitlab.johannesjh.favagtk.json"
    FLATPAK_MODULE: "favagtk"
    APP_ID: "org.gnome.gitlab.johannesjh.favagtk"
    RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
    BUNDLE: "org.gnome.gitlab.johannesjh.favagtk.flatpak"
  extends: ".flatpak"
