include: "https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml"

stages:
  - build
  - test
  - upload
  - release

flatpak:
  # builds a flatpak image
  extends: ".flatpak"
  stage: build
  image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master"
  rules:
    - if: $CI_COMMIT_TAG == null
      variables:
        PROFILE: devel
    - if: $CI_COMMIT_TAG != null
      variables:
        PROFILE: release
  variables:
    MANIFEST_PATH: "org.gnome.gitlab.johannesjh.favagtk.json"
    FLATPAK_MODULE: "favagtk"
    APP_ID: "org.gnome.gitlab.johannesjh.favagtk"
    RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
    BUNDLE: "org.gnome.gitlab.johannesjh.favagtk.flatpak"
    CONFIG_OPTS: >
      -Dprofile=${PROFILE}

upload:
  # uploads the flatpak bundle to the project's package registry
  # based on: https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs/examples/release-assets-as-generic-package
  stage: upload
  only:
    - tags
  image: curlimages/curl:latest
  script: |
    # list all environment variables for debug purposes:
    export
    # upload the flatpak bundle:
    curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${BUNDLE} ${PACKAGE_REGISTRY_URL}/${BUNDLE}

release:
  # creates a release
  # https://docs.gitlab.com/ee/ci/yaml/index.html#release
  stage: release
  only:
    - tags
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Release $CI_COMMIT_TAG"
    description: "Release created using the release-cli."
    assets:
      links:
        - name: ${BUNDLE}
          url: ${PACKAGE_REGISTRY_URL}/${BUNDLE}
