[tool.poetry]
name = "fava-desktop"
version = "0.1.0"
description = ""
authors = ["johannesjh <johannesjh@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.extras]
smart-importer = ["smart-importer"]

[tool.poetry.dev-dependencies]
fava = { path = "fava", develop = true }
PyGObject = "^3.38.0"
pytest = "^5.2"
pre-commit = "^2.9.2"
pyclean = "^2.0.0"

[tool.poetry.scripts]
fava-desktop = "fava_desktop.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
