on:
  push:
  pull_request:
name: flatpak
jobs:
  flatpak:
    name: "flatpak"
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged

    steps:
      - uses: actions/checkout@v3

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: io.github.johannesjh.favagtk.flatpak
          manifest-path: io.github.johannesjh.favagtk.json
          cache-key: flatpak-builder-${{ github.sha }}

      - name: create a github release and upload the flatpak package
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: io.github.johannesjh.favagtk.flatpak
